pull_request_rules:
  - name: Automatic merge for Dependabot PRs with patch updates
    conditions:
      - author = dependabot[bot]
      - dependabot-update-type = version-update:semver-patch
      - check-success = greet
    actions:
      merge:
        method: merge
  # - name: Automatic merge when CI has at least one approval
  #   conditions:
  #     - "#approved-reviews-by>=1"
  #   actions:
  #     merge:
  #       method: merge

  - name: "backport from 1.0.0 to 2.0.0"
    conditions:
      - label = backport
    actions:
      backport:
        branches:
          - "release/2.0.0"

queue_rules:
  - name: default
    queue_conditions:
      - check-success = greet
      - "#approved-reviews-by >= 1"
