pull_request_rules:
  - name: Automatic merge for Dependabot PRs with patch updates
    conditions:
      - author = dependabot[bot]
      - dependabot-update-type = version-update:semver-patch
      - check-success = greet
    actions:
      merge:
        method: merge
        
  - name: Automatic merge ignore Branch Protection
    conditions:
      - label = override
    actions:
      queue:
        name: override
        merge_bot_account: sxmkkunst

  - name: Add PR to merge queue when CI passes and has at least one approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success = greet
    actions:
      queue:
        name: batch-queue

  - name: "backport from 1.0.0 to 2.0.0"
    conditions:
      - label = backport
    actions:
      backport:
        branches:
          - "release/2.0.0"

queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by >= 1"
  - name: batch-queue
    queue_conditions:
      - "#approved-reviews-by >= 1"
    batch_size: 3
  - name: override
    queue_conditions:
      - label = override
    branch_protection_injection_mode: none
