name: Test Workflow

on:
  pull_request:
  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Tell us tests passed
      run: echo "Tests passed"
    - name: Pass tests
      run: exit 0
