name: Test Workflow

on:
  pull_request:
  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Tell us tests failed
      run: echo "Tests failed"
    - name: Tests failed
      run: exit 1
